"""create instagram tables

Revision ID: 3a61de5660d0
Revises: 
Create Date: 2026-07-13 09:35:18.154918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a61de5660d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.Column('mediacount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_users_username'), 'instagram_users', ['username'], unique=True)
    op.create_table('mutual_followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mutual_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['instagram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutual_followers')
    op.drop_index(op.f('ix_instagram_users_username'), table_name='instagram_users')
    op.drop_table('instagram_users')
    # ### end Alembic commands ###
