"""added a constraint unique_mutual_followers

Revision ID: 85638eaaac33
Revises: 35c01812ff8d
Create Date: 2026-07-17 14:42:58.191542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85638eaaac33'
down_revision: Union[str, Sequence[str], None] = '35c01812ff8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_mutual_follower', 'mutual_followers', ['user_id', 'mutual_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_mutual_follower', 'mutual_followers', type_='unique')
    # ### end Alembic commands ###
