"""added mutual_usernames

Revision ID: 85d1eac22cf8
Revises: 3a61de5660d0
Create Date: 2026-07-13 15:25:35.320481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d1eac22cf8'
down_revision: Union[str, Sequence[str], None] = '3a61de5660d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutual_followers', sa.Column('mutual_user_username', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mutual_followers', 'mutual_user_username')
    # ### end Alembic commands ###
