"""added profile pic in instagram user tabel

Revision ID: 8aa0d08276bf
Revises: c46cf760bec6
Create Date: 2026-07-15 14:03:30.760294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa0d08276bf'
down_revision: Union[str, Sequence[str], None] = 'c46cf760bec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_users', sa.Column('profile_pic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_users', 'profile_pic')
    # ### end Alembic commands ###
