"""added username in mutual followers

Revision ID: a37075df6a8e
Revises: 85d1eac22cf8
Create Date: 2026-07-15 11:13:08.356665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37075df6a8e'
down_revision: Union[str, Sequence[str], None] = '85d1eac22cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutual_followers', sa.Column('username', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_mutual_followers_username'), 'mutual_followers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutual_followers_username'), table_name='mutual_followers')
    op.drop_column('mutual_followers', 'username')
    # ### end Alembic commands ###
