"""removed uniqe from username in mutual followers

Revision ID: c46cf760bec6
Revises: a37075df6a8e
Create Date: 2026-07-15 11:58:17.143075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46cf760bec6'
down_revision: Union[str, Sequence[str], None] = 'a37075df6a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutual_followers_username'), table_name='mutual_followers')
    op.create_index(op.f('ix_mutual_followers_username'), 'mutual_followers', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutual_followers_username'), table_name='mutual_followers')
    op.create_index(op.f('ix_mutual_followers_username'), 'mutual_followers', ['username'], unique=True)
    # ### end Alembic commands ###
